/* tslint:disable */
/* eslint-disable */
/**
 * Snippets API
 * Test description
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Manager
 */
export interface Manager {
    /**
     * 
     * @type {number}
     * @memberof Manager
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof Manager
     */
    user: number;
    /**
     * 
     * @type {string}
     * @memberof Manager
     */
    readonly fullName?: string;
}

/**
 * Check if a given object implements the Manager interface.
 */
export function instanceOfManager(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;

    return isInstance;
}

export function ManagerFromJSON(json: any): Manager {
    return ManagerFromJSONTyped(json, false);
}

export function ManagerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Manager {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'user': json['user'],
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
    };
}

export function ManagerToJSON(value?: Manager | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
    };
}

