# Generated by Django 4.1.1 on 2022-11-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0016_alter_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
