# Generated by Django 4.1.1 on 2022-12-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0021_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Назначен'), (1, 'Проведён'), (2, 'Отменён')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
